import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import prettier from "eslint-config-prettier";

export default [
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  js.configs.recommended,
  // Configuration for TypeScript files
  {
    files: ["**/*.ts"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        // Node 18+ web platform globals
        fetch: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...prettier.rules,
      // Enforce no explicit any - use proper types or type guards instead
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "no-undef": "warn",
      "no-console": "off",
    },
  },
  // Configuration for JavaScript files (scripts)
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        // Node 18+ web platform globals
        fetch: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
      },
    },
    rules: {
      ...prettier.rules,
      "no-console": "off",
      "no-undef": "warn",
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
    },
  },
  // SvelteKit web dashboard (browser + SSR; Svelte 5 runes)
  {
    files: ["web/**/*.ts", "web/**/*.js"],
    languageOptions: {
      globals: {
        // DOM
        document: "readonly",
        window: "readonly",
        location: "readonly",
        history: "readonly",
        navigator: "readonly",
        performance: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        queueMicrotask: "readonly",
        scrollTo: "readonly",
        getComputedStyle: "readonly",
        // Browser APIs
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLAnchorElement: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        EventTarget: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        FocusEvent: "readonly",
        File: "readonly",
        FileList: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
        WebSocket: "readonly",
        EventSource: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        btoa: "readonly",
        atob: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        addEventListener: "readonly",
        removeEventListener: "readonly",
        dispatchEvent: "readonly",
        self: "readonly",
        // SvelteKit runtime
        App: "readonly",
        // Node.js types (web/ may reference them in API routes)
        NodeJS: "readonly",
        global: "readonly",
        require: "readonly",
        // Browser APIs (continued)
        DOMException: "readonly",
        PerformanceObserver: "readonly",
        SVGAElement: "readonly",
        Notification: "readonly",
        Text: "readonly",
        XMLHttpRequest: "readonly",
        WebAssembly: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLOptionElement: "readonly",
        // Sentry runtime debug flag
        __SENTRY_DEBUG__: "readonly",
        // Svelte 5 runes (recognized as identifiers by ESLint outside svelte-eslint-parser)
        $state: "readonly",
        $derived: "readonly",
        $effect: "readonly",
        $props: "readonly",
        $bindable: "readonly",
        $inspect: "readonly",
        $host: "readonly",
      },
    },
  },
  // Cloudflare Workers runtime (workers/discord-proxy/)
  {
    files: ["workers/**/*.ts", "workers/**/*.js"],
    languageOptions: {
      globals: {
        addEventListener: "readonly",
        ExecutionContext: "readonly",
        ExportedHandler: "readonly",
        ExportedHandlerFetchHandler: "readonly",
        ExportedHandlerScheduledHandler: "readonly",
        ScheduledEvent: "readonly",
        KVNamespace: "readonly",
        D1Database: "readonly",
        DurableObjectNamespace: "readonly",
        DurableObjectState: "readonly",
        DurableObjectStorage: "readonly",
        R2Bucket: "readonly",
        Queue: "readonly",
        WebSocketPair: "readonly",
        caches: "readonly",
      },
    },
  },
];
