// SPDX-License-Identifier: LicenseRef-ANW-1.0
/**
 * Pawtropolis Tech -- src/features/badges/snapshotResolve.ts
 * WHAT: Build ResolvedBadge values from the on-disk live-server snapshot
 *       files (docs/internal-info/ROLES.md, docs/internal-info/CHANNELS.md).
 * WHY: Lets us render the full badge set offline (e.g. in CI, in the
 *       generate-badges script, before the bot has had a chance to do its
 *       first Discord fetch). Bypasses the resolver and Discord client.
 *
 * The snapshot files are auto-generated by the audit pipeline and contain
 * canonical name + color + ID for every role and channel. Parsing them is
 * regex-light: simple Markdown tables.
 */

import fs from "node:fs";
import {
  DISCORD_BLURPLE,
  DISCORD_NEUTRAL_PILL,
  intToHex,
  normalizeHex,
  readableTextOn,
  tintForPill,
} from "./color.js";
import type { BadgeDefinition, ResolvedBadge } from "./types.js";

export type RoleSnapshotEntry = { name: string; colorHex: string };
export type ChannelSnapshotEntry = { name: string };

export type SnapshotData = {
  rolesById: Map<string, RoleSnapshotEntry>;
  channelsById: Map<string, ChannelSnapshotEntry>;
};

/**
 * Parse the "Role Hierarchy (by position)" table for color, then the "All
 * Role IDs (for reference)" table for the canonical name -> id mapping.
 * Returns a discord-id keyed map.
 */
export function parseRolesSnapshot(markdown: string): Map<string, RoleSnapshotEntry> {
  const colorByName = new Map<string, string>();
  const hierMatch = /## Role Hierarchy[^\n]*\n([\s\S]*?)(?:\n## |$)/.exec(markdown);
  if (hierMatch) {
    const lines = hierMatch[1]!.split(/\r?\n/);
    for (const line of lines) {
      const m = /^\|\s*\d+\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/.exec(line);
      if (!m) continue;
      const name = m[1]!.trim();
      const color = m[2]!.trim();
      if (name && color && !colorByName.has(name)) {
        colorByName.set(name, color);
      }
    }
  }

  const idByName = new Map<string, string>();
  const idsMatch = /## All Role IDs[^\n]*\n([\s\S]*?)(?:\n## |$)/.exec(markdown);
  if (idsMatch) {
    const lines = idsMatch[1]!.split(/\r?\n/);
    for (const line of lines) {
      const m = /^\|\s*([^|]+?)\s*\|\s*`(\d{5,30})`\s*\|/.exec(line);
      if (!m) continue;
      idByName.set(m[1]!.trim(), m[2]!);
    }
  }

  const out = new Map<string, RoleSnapshotEntry>();
  for (const [name, id] of idByName) {
    const rawColor = colorByName.get(name) ?? "default";
    // Empty string signals "no Discord color"; the renderer treats that as a
    // neutral pill (matches how Discord renders no-color role mentions).
    const colorHex = rawColor.startsWith("#") ? normalizeHex(rawColor) : "";
    out.set(id, { name, colorHex });
  }
  return out;
}

/**
 * Parse the channel hierarchy. Each `### Category` block contains a
 * `| Channel | Type | ID | NSFW | Slowmode |` table.
 */
export function parseChannelsSnapshot(
  markdown: string,
): Map<string, ChannelSnapshotEntry> {
  const out = new Map<string, ChannelSnapshotEntry>();
  const lines = markdown.split(/\r?\n/);
  for (const line of lines) {
    const m = /^\|\s*([^|]+?)\s*\|\s*[^|]+?\s*\|\s*`(\d{5,30})`\s*\|/.exec(line);
    if (!m) continue;
    const name = m[1]!.trim();
    if (name === "Channel" || name === "------") continue;
    const id = m[2]!;
    if (!out.has(id)) out.set(id, { name });
  }
  return out;
}

export function loadSnapshot(
  rolesPath: string,
  channelsPath: string,
): SnapshotData {
  const rolesText = fs.readFileSync(rolesPath, "utf8");
  const channelsText = fs.readFileSync(channelsPath, "utf8");
  return {
    rolesById: parseRolesSnapshot(rolesText),
    channelsById: parseChannelsSnapshot(channelsText),
  };
}

function nowIso(): string {
  return new Date().toISOString();
}

export function resolveFromSnapshot(
  def: BadgeDefinition,
  snapshot: SnapshotData,
  guildId: string,
): ResolvedBadge {
  if (def.kind === "role" && def.discordId) {
    const entry = snapshot.rolesById.get(def.discordId);
    if (entry) {
      // Preserve "" (no Discord color) so the renderer uses the neutral
      // pill style instead of forcing the role into blurple.
      const colorHex = entry.colorHex;
      const bg = colorHex ? tintForPill(colorHex, 0.28) : DISCORD_NEUTRAL_PILL;
      return {
        id: def.id,
        kind: "role",
        guildId,
        discordId: def.discordId,
        displayName: def.label || entry.name,
        prefix: "@",
        suffix: def.suffix,
        colorHex,
        backgroundHex: bg,
        foregroundHex: readableTextOn(bg),
        linkUrl: def.linkUrl,
        stale: false,
        resolvedAt: nowIso(),
        gradient: def.gradient,
        holographic: def.holographic,
      };
    }
  }
  if (def.kind === "channel" && def.discordId) {
    const entry = snapshot.channelsById.get(def.discordId);
    if (entry) {
      return {
        id: def.id,
        kind: "channel",
        guildId,
        discordId: def.discordId,
        displayName: def.label || entry.name,
        prefix: "#",
        suffix: def.suffix,
        colorHex: DISCORD_BLURPLE,
        backgroundHex: DISCORD_NEUTRAL_PILL,
        foregroundHex: readableTextOn(DISCORD_NEUTRAL_PILL),
        linkUrl: def.linkUrl,
        stale: false,
        resolvedAt: nowIso(),
      };
    }
  }
  // Fallback: use label or id as display name; mark stale because the
  // snapshot did not cover this entity.
  const fallbackName = def.label || (def.kind === "channel" ? "unknown-channel" : "unknown-role");
  const prefix: ResolvedBadge["prefix"] =
    def.kind === "channel" ? "#" : def.kind === "user" ? "@" : def.kind === "role" ? "@" : "";
  return {
    id: def.id,
    kind: def.kind,
    guildId,
    discordId: def.discordId,
    displayName: fallbackName,
    prefix,
    suffix: def.suffix,
    colorHex: DISCORD_BLURPLE,
    backgroundHex: DISCORD_NEUTRAL_PILL,
    foregroundHex: readableTextOn(DISCORD_NEUTRAL_PILL),
    linkUrl: def.linkUrl,
    stale: true,
    resolvedAt: nowIso(),
  };
}
